version: '3.3'
services:
 postgres:
     image: postgres:10
     restart: always
     container_name: postgres
     hostname: postgres
     ports:
      - "5432:5432"
     environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       PGDATA: "/var/lib/postgresql/data"
     volumes:
      - ./data/postgres:/var/lib/postgresql/data  
     env_file:
      - ./secret/variables.env

 redmine:
     build: ./redmine
     container_name: redmine
     hostname: redmine
     restart: unless-stopped
     depends_on:
        - postgres
     links:
        - postgres
     expose:
      - "3000"
     volumes:
        - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
        - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
        - ./storage/docker_redmine-data:/usr/src/redmine/files
 
 nginx:
    
     build: ./frontend
     container_name: nginx
     hostname: nginx
     volumes:
       - ./logs/nginx/:/var/log/nginx/
  
     ports:
      - "3000:3000"
     links:
      - redmine
     depends_on:
      - redmine
     command: ["nginx", "-g", "daemon off;"]
     restart: unless-stopped
