version: '3.3'
services:
 db:
     image: postgres:10
     container_name: db
     volumes:
       - ./storage/postgresql-data:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: "superstrongpasswd123"
       POSTGRES_DB: "redmine"
       PGDATA: "/var/lib/postgresql/data"
       POSTGRES_HOST_AUTH_METHOD: trust
     networks:
      - network1
 
 redmine:
     networks:
      - network1
     build: ./redmine
     restart: always
     depends_on:
        - postgres
     links:
        - postgres
     ports:
        - 80:3000
     volumes:
        - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
        - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
        - ./storage/docker_redmine-data:/usr/src/redmine/files
     environment:
        REDMINE_DB_POSTGRES: "postgres"
        REDMINE_DB_USERNAME: "postgres"
        REDMINE_DB_PASSWORD: "superstrongpasswd123"
        REDMINE_DB_DATABASE: "redmine"
        REDMINE_SECRET_KEY_BASE: "…"

 nginx:
         nginx:
    build: ./nginx
    container_name: nginx
    #environment:
    #  TZ: Asia/Tokyo # Please set time zone if you want to change it.
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    hostname: nginx
    ports:
      - "3000:3000"
      - "443:443"
    links:
      - redmine
    depends_on:
      - redmine
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped
    networks:
      - network1


networks:
   network1:
      driver: bridge
