version: '3.3'
services:
 postgres:
     image: postgres:10
     volumes:
       - ./storage/postgresql-data:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: "strong_pass"
       POSTGRES_DB: "redmine"
       PGDATA: "/var/lib/postgresql/data"
       "POSTGRES_HOST_AUTH_METHOD=trust"
     networks:
      - network1
 
 redmine:
     networks:
      - network1
     build: ./redmine
     restart: always
     depends_on:
        - postgres
     ports:
        - 80:3000
     volumes:
        - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
        - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
        - ./storage/docker_redmine-data:/usr/src/redmine/files
     environment:
        REDMINE_DB_POSTGRES: "postgres"
        REDMINE_DB_USERNAME: "postgres"
        REDMINE_DB_PASSWORD: "superstrongpasswd123"
        REDMINE_DB_DATABASE: "redmine"
        REDMINE_SECRET_KEY_BASE: "…"

 frontend:
         image: nginx
         restart: always
         networks:
            - network1


networks:
   network1:
      driver: bridge
