version: '3.3'

volumes:
 database_data:
  driver: local

services:
    db:
        image: postgres:10
        restart: always
        ports:
         - 5432:5432
        environment: 
          POSTGRES_PASSWORD: super_strong_passwd_123
          POSTGRES_DB: "redmine"
          PGDATA: "/var/lib/postgresql/data"
        volumes:
           - ./storage/postgresql-data:/var/lib/postgresql/data
 


    redmine:
     build: ./redmine
     restart: always
     depends_on:
        - db
     ports:
        - 80:3000
     volumes:
        - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
        - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
        - ./storage/docker_redmine-data:/usr/src/redmine/files
     environment:
        REDMINE_DB_POSTGRES: "postgres"
        REDMINE_DB_USERNAME: "postgres"
        REDMINE_DB_PASSWORD: "super_strong_passwd_123"
        REDMINE_DB_DATABASE: "redmine"
        REDMINE_SECRET_KEY_BASE: "…"


    frontend:
         image: nginx
         restart: always
