version: '3.3'
services:
 postgres:
     build: ./db
     restart: always
     container_name: postgres
     environment:
       POSTGRES_USER: "postgres"
       POSTGRES_PASSWORD: "postgres"
       POSTGRES_DB: "postgres"
       PGDATA: "/var/lib/postgresql/data"
      # POSTGRES_HOST_AUTH_METHOD: "trust"
     volumes:
      - ./data/postgres:/var/lib/postgresql/data  
     
     networks:
      - network1
 redmine:
     networks:
      - network1
     build: ./redmine
     container_name: redmine
     restart: always
     depends_on:
        - postgres
     links:
        - postgres
     ports:
        - 3000:3000
     volumes:
        - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
        - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
        - ./storage/docker_redmine-data:/usr/src/redmine/files
     #environment:
     #   - DB_PORT=tcp://db:5432
 
 
 #nginx:
    
   #  image: nginx
    # container_name: nginx
    # volumes:
   #    - ./logs/nginx/:/var/log/nginx/
  #     - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
  #   hostname: nginx
  #   ports:
   #   - "3000:3000"
   #   - "443:443"
   #  links:
   #   - redmine
  #   depends_on:
   #   - redmine
  #   command: ["nginx", "-g", "daemon off;"]
   #  restart: unless-stopped
   #  networks:
  #    - network1


networks:
   network1:
      driver: bridge
